name: "Solarman Statistic"
description: "Add-on for Solarman statistics with user profile page"
version: "0.0.7"
slug: "solarman_statistic"
url: "https://github.com/SorochanRoman/solarman-statistic-ha"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
init: false
panel_icon: mdi:chart-line
panel_title: "Solarman Statistic"
panel_admin: false
ingress: true
ingress_port: 8099
homeassistant_api: true
hassio_api: true
changelog: "Added Home Assistant entities search and API integration"