name: "Solarman Statistic"
description: "Add-on for Solarman statistics"
version: "0.0.3"
slug: "solarman_statistic"
url: "https://github.com/SorochanRoman/solarman-statistic-ha"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
init: false
panel_icon: mdi:chart-line